##
## EPITECH PROJECT, 2023
## antman_giantman
## File description:
## dsk
##

SRC_ANT = antman/

SRC_GIANT = giantman/

all:
	make -C antman/ -s
	make -C giantman/ -s

clean:
	make clean -C antman/ -s
	make clean -C giantman/ -s

fclean:
	make fclean -C antman/ -s
	make fclean -C giantman/ -s

re: fclean all
