##
## EPITECH PROJECT, 2023
## Makefile
## File description:
## Makefile
##

all:
	make -C generator/
	make -C solver/

clean:
	make -C generator/ $@
	make -C solver/ $@

fclean:
	make -C generator/ $@
	make -C solver/ $@

re:
	make -C generator/ $@
	make -C solver/ $@

gcovr:
	make -C generator/ $@
	make -C solver/ $@

.PHONY: all clean fclean gcovr
